# Test technique - C Elegans

Dans le cadre du projet C Elegans organisé par l'association 42AI, votre candidature s'accompagne de la réalisation de ce test technique afin d'évaluer vos compétences techniques et votre capacité à résoudre des problématiques que vous n'avez pas rencontrer. Terminer totalement ce test n'est pas impérative pour être sélectionné. Sera jugé également votre esprit scientifique / logique, votre capacité à structurer vos expériences et votre pédagogie en expliquant ce que vous avez réalisé.

## Durée estimée:
Le temps estimé afin de réaliser ce test est de 2h pour une personne ayant la majorité des connaissances pour le réaliser (vous y passerez plus de temps s'il est nécessaire que vous appreniez quelques connaissances, cela est normal. Il est également normal que certains exercices soient durs). Vous bénéficiez d'une durée de 24h au moment de la communication du test afin de le retourner.

Si vous tombez sur des ressources vous permettant de réaliser une question ou un exercice ou le problème ouvert, vous pouvez le mentionner et dire en quoi cette ressource vous a aidé.

## Sommaire:

### [Questions générales](#ss-section-1)

### [Exercices basiques en python](#ss-section-2)

### [Problème ouvert](#ss-section-3)

Au sein de chaque partie les exercices sont organisés du plus facile au plus dur. Il **N'EST PAS** impératif de terminer une partie avant de faire la suivante. (Si vous boquez, passer à l'exercice suivant ou à la partie suivante !!)

---
---
<a id='ss-section-1'></a>
## Questions générales

### Premiere question:
En intelligence artificielle, les jeux de données utilisés afin d'entraîner des modèles de *Machine Learning* ou de *Deep Learning* sont souvent divisés en 3 parties.
* Le premier sous-ensembles est appelé ensemble d'entraînement (*train / training set* en anglais), quel est le nom des 2 autres sous-ensembles ?
* Quel est le rôle des 2 sous-ensembles de données que vous avez donné ?
---

Les noms de deux autres sous-ensembles sont "validation data set" et "test data set".
Le role du premier est de fournir une evaluation ajustee du modele fait avec training set et d'ajuster les hyperparametres.
Le test data set sert pour evaluer un ajustement final du modele. 

---
### Deuxième question:
Toujours en intelligence articielle, afin d'entraîner un modèle (de *Machine Learning* ou *Deep Learning*), les prédictions du modèles sont évalués vis à vis des sorties (*outputs* ou *targets*).

* Comment appelle-t-on une fonction permettant de faire cette évaluation ?
* Cité une fonction utilisée pour un problème de régression linéaire.
* Cité une fonction utilisée pour un problème de classification.
---

*... Votre réponse ... (double cliquer sur cette cellule et éditer - le format de la cellule est du Markdown)*

---
### Troisième question:
Question d'ordre mathématiques. Soit une matrice $\mathbf{M}$ à coefficients réelles, un vecteurs $V$, la matrice identié $\mathbf{I}$ et une constante $\lambda$ tels que:
$$
\mathbf{M} = \begin{bmatrix}
                    x_{11} & x_{12} & x_{13} \\
                    x_{21} & x_{22} & x_{23} \\
                    x_{31} & x_{32} & x_{33}
             \end{bmatrix}
$$

$$
V = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}
$$

$$
I = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

$$
\lambda = 5
$$

* Calculer:
$$
(\mathbf{M} + \lambda \mathbf{I}) V
=
\left(
\begin{bmatrix}
  x_{11} & x_{12} & x_{13} \\
  x_{21} & x_{22} & x_{23} \\
  x_{31} & x_{32} & x_{33}
\end{bmatrix}
- 5 \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix}
\right)
\cdot 
\begin{bmatrix} 1 \\ 1 \\ 0\end{bmatrix}
$$
---

*... Votre réponse ... (double cliquer sur cette cellule et éditer - le format de la cellule est du Markdown)*

*Vous pouvez remplir l'un des éléments suivants et supprimer les deux autres.*
$$
\begin{bmatrix}
... & ... & ... \\
... & ... & ... \\
... & ... & ...
\end{bmatrix}
$$

$$
\begin{bmatrix}
... \\
... \\
...
\end{bmatrix}
$$

$$
...
$$

---
### Quatrième question:
Considérons que vous êtes devant la porte d'une pièce. Dans cette pièce se trouve $10$ ampoules et chaque ampoule est strictement indépendantes les unes des autres.

Chaque ampoule à une probabilité de $p = 0.7$ d'être allumée au moment où vous allez entrer dans la pièce (et donc une probabilité de $0.3$ d'être éteinte).

* Quelle est la probabilité qu'une seule ampoule soit étteinte ?

---

*... Votre réponse ... (double cliquer sur cette cellule et éditer - le format de la cellule est du Markdown)*

---
---
<a id='ss-section-2'></a>
## Exercices basiques en python

### Premiere exercice: Multiple de 3 et de 5

Coder une fonction qui prend un nombre n en paramètre et qui additionne tous les multiples de 3 et 5 strictement inférieur à n.
```python
def sum_of_multiple_3_5(n: int) -> int:
    ...
```


**Exemple:**
```python
sum_of_multiple_3_5(4)
3

sum_of_multiple_3_5(6)
8

sum_of_multiple_3_5(16)
60

sum_of_multiple_3_5(3)
0

sum_of_multiple_3_5(5)
3

sum_of_multiple_3_5(15)
45
```
---

In [ ]:
#... Votre solution (cette cellule est au format Python)...
def sum_of_multiple_3_5(n: int) -> int:
    """ Coder votre fonction ici.
    """
    resultat = 0
    for i in range(1, n):
        if i %3 == 0 or i%5 == 0 and i < n:
            resultat += i
    print (resultat)

    pass


---
### Deuxième exercice:
Coder une fonction qui prend un nombre entier $n$ en paramètre et qui élève chaque chiffre du nombre au carré:

**Exemple**:
* square_digit(2) donne 4
* square_digit(8) donne 64
* square_digit(483) donne 16649


```python
def square_digit(n):
    ...
```

---

In [1]:
#... Votre solution (cette cellule est au format Python)...
def square_digit(n) -> int:
    s = ''
    for i in str(n):
        s += str(int(i)**2)
    print(int(s)) 
    
    pass

---
"""### Troisème exercice:

Soit une list d'entiers `lst_int`. Le but de l'exercice est de coder une fonction donnant l'indice $i$ où la somme des entiers à gauche de $i$ (avec l'entier à la position $i$ inclut) est égale à la somme des entiers à la droite de $i$. S'il n'y a pas d'index permettant cela, votre fonction doit retourner $-1$.

python'''"""
def balance_list_int(lst_int: list) -> int:
    ###... Your code ...
    
**Exemples**
```python
# exemple 1
lst_int_1 = [12]
balance_list_int(lst_int_1)
-1

# exemple 2
lst_int_2 = [1, 1, 2]
balance_list_int(lst_int_2)
1

# exemple 3
lst_int_3 = [1, 5, 0, 9, 1, 2, 8, 4]
balance_list_int(lst_int_3)
3
```


---

In [ ]:
#... Votre solution (cette cellule est au format Python)...
def balance_list_int(lst_int: int) -> int:
        """ Coder votre fonction ici.
        """
        resultat = -1
        for i in range(0, len(lst_int)):
                aleft = 0
                aright = 0
                for j in range (0, i+1):
                        aleft += lst_int[j]
                for j in range(i + 1, len(lst_int)):
                        aright += lst_int[j]
                if aleft == aright:
                        resultat = i
                        print(resultat)
                        exit()
        print(resultat)


lst_int = [1, 5, 0, 9, 1, 2, 8, 6]
balance_list_int(lst_int)
pass

---
### Quatrième exercice:
Soit un numpy array `grid` de shape (10,10) représentant une grille sur laquelle il peut y avoir des bombes. Coder une fonction qui calcul le nombre de bombe **autour** de chaque case de la grille.

**Exemple**:
```python
# Exemple 1
grid_1 = np.array([[0, 0, 0, 1, 1, 0, 0, 0, 1, 1],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                   [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
                   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                   [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
                   [0, 0, 0, 0, 0, 0, 1, 1, 0, 0]])

bomb_map = bomb_mapping(grid_1)
print(bomb_map)
[[0 0 1 1 1 1 0 1 1 1]
 [1 1 2 2 2 1 0 1 2 2]
 [1 0 1 0 1 1 1 0 0 0]
 [1 2 2 2 2 2 2 2 1 1]
 [0 1 0 2 2 4 2 2 0 1]
 [0 1 1 3 3 3 2 2 1 1]
 [0 0 0 1 1 2 1 0 0 0]
 [0 0 0 2 2 2 0 1 1 1]
 [0 0 0 1 0 2 2 3 1 1]
 [0 0 0 1 1 2 1 2 2 1]]


# Exemple 2
grid_2 = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                   [0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
                   [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
                   [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
                   [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                   [1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
                   [0, 0, 0, 0, 0, 0, 1, 1, 0, 0]])
bomb_map_2 = bomb_mapping(grid_2)
print(bomb_map_2)
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 0 1 0 1 1 1 0 0 0]
 [1 2 2 2 2 2 2 1 0 0]
 [0 2 1 3 2 4 2 1 0 0]
 [1 4 3 5 3 3 2 1 0 0]
 [2 4 4 4 1 2 1 0 0 0]
 [4 5 4 4 2 2 0 1 1 1]
 [2 3 3 2 0 2 2 3 1 1]
 [2 2 1 1 1 2 1 2 2 1]]
```

---

In [ ]:
import numpy as np

#... Votre solution (cette cellule est au format Python)...
def bomb_mapping(grid: np.array) -> np.array:
    """ Coder votre fonction ici
    """
    pass

---
---
<a id='ss-section-3'></a>
## Problème ouvert

Le but de ce problème est de faire un programme permettant de détecter et dénombrer les différents *"blobs"* au sein d'images fournies (`"white_blobs_black_bg.png"` et `"white_blobs_black_bg_2.png"`) avec ce notebook python.

![image_blobs_1](white_blobs_black_bg_1.png)
![image_blobs_2](white_blobs_black_bg_2.png)

Pour cela vous êtes libre d'utiliser les librairies python que vous souhaité.

En fonction de vos connaissances actuelles et du hasard au cours de votre recherche, il se peut que vous tombiez rapidement sur des fonctions vous permettant de réaliser les différentes tâches en quelques lignes de codes. Si ce n'est pas le cas, ne vous inquiétez pas, prenez le temps de décomposer les différentes tâches:
* détection
* dénombrement

Pour rappel, vous n'est pas évalué uniquement sur votre capacité à réussir mais sur votre démarche, la clarté de votre code et votre capacité à assimiler et expliquer ce que votre code fait (ainsi les commentaires au sein de votre code sont très appréciés).

À titre d'illustration, voici la représentation de l'étape de détection des blobs pour les 2 images:

![image_detection_blobs_1](blobs_detect_img_bw_1.png)
![image_detection_blobs_2](blobs_detect_img_bw_2.png)

Comme vous pouvez le voir, nous ne vous demandons pas que la detection soit absolument parfaite en ne coupant pas de blobs. Ce n'est pas grave non plus si quelques blobs sont manqués.

Une fonction permettant de dénombrer le nombre de blobs donne:
* pour la première image: $13$ blobs
* pour la seconde image: $16$ blobs

In [ ]:
# En fonction si vous utiliser conda ou pip pour votre gestion de librairie python décommenter les 3 premières lignes ou les 3 dernières

# %pip3 install matplotlib
# %pip3 install numpy
# %pip3 install opencv-python
# %pip install scikit-image

# %conda install -c conda-forge matplotlib
# %conda install numpy
# %conda install -c conda-forge opencv
# %conda install scikit-image

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import cv2
import skimage

In [ ]:
img_1 = mpimg.imread('white_blobs_black_bg_1.png')
img_2 = mpimg.imread('white_blobs_black_bg_2.png')

print("shape de l'image_1 RGB: ", img_1.shape)
print("shape de l'image_2 RGB: ", img_2.shape)
# L'output est un numpy array de 200 x 200 x 3 qui correspond à 3 'tableaux' 
# de 200 pixels de haut sur 200 pixels de large pour les 3 canaux de couleurs Rouge, Vert Bleu

# Conversion de img (200, 200, 3) en img_bw (200, 200)
img_bw_1 = cv2.cvtColor(img_1, cv2.COLOR_RGB2GRAY)
img_bw_2 = cv2.cvtColor(img_2, cv2.COLOR_RGB2GRAY)
print("shape de l'image_1 niveau de gris: ", img_bw_1.shape)
print("shape de l'image_2 niveau de gris: ", img_bw_2.shape)

In [ ]:
plt.imshow(img_bw_1, cmap='Greys_r')

In [ ]:
plt.imshow(img_bw_2, cmap='Greys_r')

In [ ]:
# À vous de jouer !